import streamlit as st
import joblib
import io

# 1. Page Configuration (Must be the first Streamlit command)
st.set_page_config(page_title="News Classifier ML", layout="centered", page_icon="📰")

# 2. Load Models and Define Categories
@st.cache_resource
def load_models():
    # These files must be generated by running your training script first
    try:
        bayes = joblib.load('bayes_model.pkl')
        logistic = joblib.load('logistic_model.pkl')
        svm = joblib.load('svm_model.pkl')
        return {"Bayes": bayes, "Logistic": logistic, "SVM": svm}
    except FileNotFoundError:
        return None

models = load_models()
# AG News labels: 1-World, 2-Sports, 3-Business, 4-Sci/Tech
category_map = {1: "World", 2: "Sports", 3: "Business", 4: "Sci/Tech"}

# 3. Initialize Session State for Algorithm selection
if "selected_algo" not in st.session_state:
    st.session_state.selected_algo = "Bayes"

# --- Helper Function: Algorithm Grid ---
def render_algo_grid(tab_key):
    st.write("### Algorithm:")
    col1, col2, col3 = st.columns(3)
    
    with col1:
        if st.button("Bayes", key=f"btn_bayes_{tab_key}", use_container_width=True):
            st.session_state.selected_algo = "Bayes"
    with col2:
        if st.button("Logistic", key=f"btn_log_{tab_key}", use_container_width=True):
            st.session_state.selected_algo = "Logistic"
    with col3:
        if st.button("SVM", key=f"btn_svm_{tab_key}", use_container_width=True):
            st.session_state.selected_algo = "SVM"
    
    st.info(f"Currently selected: **{st.session_state.selected_algo}**")

# --- UI Header ---
st.title("📰 News Classification")

if models is None:
    st.error("⚠️ Model files (.pkl) not found! Please run your training script first.")
    st.stop()

# --- Tabs Implementation ---
tab1, tab2 = st.tabs(["Predict by Text", "Predict by File"])

# --- TAB 1: PREDICT BY TEXT ---
with tab1:
    news_input = st.text_area(
        label="Paste news article content here...",
        placeholder="Type or paste the news text you want to classify...",
        height=200,
        key="main_text_area"
    )

    render_algo_grid("text_tab")

    if st.button("Classify News", type="primary", use_container_width=True):
        if not news_input.strip():
            st.warning("Please enter some news text first.")
        else:
            # Perform Prediction
            selected_model = models[st.session_state.selected_algo]
            prediction = selected_model.predict([news_input])[0]
            label = category_map.get(prediction, "Unknown")
            
            st.markdown("---")
            st.subheader(f"Result: :blue[{label}]")
            st.caption(f"Model used: {st.session_state.selected_algo}")

# --- TAB 2: PREDICT BY FILE ---
with tab2:
    uploaded_file = st.file_uploader("Upload your news file (.txt)", type=['txt'])
    
    render_algo_grid("file_tab")

    if st.button("Classify File", type="primary", use_container_width=True):
        if uploaded_file is None:
            st.error("Please upload a .txt file first!")
        else:
            # Read and decode the text file
            raw_text = uploaded_file.read().decode("utf-8")
            
            if not raw_text.strip():
                st.error("The uploaded file is empty.")
            else:
                # Show a preview of the file content
                with st.expander("Show uploaded text content"):
                    st.write(raw_text)

                # Perform Prediction
                selected_model = models[st.session_state.selected_algo]
                prediction = selected_model.predict([raw_text])[0]
                label = category_map.get(prediction, "Unknown")
                
                st.markdown("---")
                st.subheader(f"Result: :green[{label}]")
                st.success(f"Successfully analyzed file content using {st.session_state.selected_algo}.")
